version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: my_postgres_container
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: highlyStrongPassword
      POSTGRES_DB: booking_app